version: '3'

services: 
    zookeeper:
        image: "zookeeper:latest"
        container_name: "mc-zooKeeper"
        ports: 
            - 2181:2181
        networks: 
            tap:
                ipv4_address: "10.0.100.22"
    kafka:
        build: kafka/
        container_name: "mc-kafka"
        environment: 
            - KAFKA_ACTION=start-kafka
        depends_on: 
            - zookeeper
        ports: 
            - 9092:9092
        networks: 
            tap:
                ipv4_address: "10.0.100.23"

    spark:
        build: spark/
        container_name: "mc-spark"
        depends_on: 
            - zookeeper
            - kafka
        networks: 
            tap:
                ipv4_address: "10.0.100.28"
    
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.1"
        container_name: "mc-elasticsearch"
        environment:
            - node.name=esMC
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=esMC
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
              soft: -1
              hard: -1
        ports:
            - 9200:9200
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data/
        networks: 
            tap:
                ipv4_address: "10.0.100.51"

volumes: 
    elasticsearch:

networks: 
    tap:
        ipam:
            driver: default
            config: 
                - subnet: 10.0.100.0/24 