version: '3'

services: 
    zookeeper:
        image: "zookeeper:latest"
        container_name: "mc-zooKeeper"
        ports: 
            - 2181:2181
        networks: 
            tap:
                ipv4_address: "10.0.100.22"
    kafka:
        build: kafka/
        container_name: "mc-kafka"
        environment: 
            - KAFKA_ACTION=start-kafka
        depends_on: 
            - zookeeper
        ports: 
            - 9092:9092
        networks: 
            tap:
                ipv4_address: "10.0.100.25"
    
networks: 
    tap:
        ipam:
            driver: default
            config: 
                - subnet: 10.0.100.0/24 