version: '3'

services: 
    zookeeper:
        image: "zookeeper:latest"
        container_name: "mc-zooKeeper"
        ports: 
            - 2181:2181
        networks: 
            tap:
                ipv4_address: "10.0.100.22"
    kafka:
        build: kafka/
        container_name: "mc-kafka"
        environment: 
            - KAFKA_ACTION=start-kafka
        depends_on: 
            - zookeeper
        ports: 
            - 9092:9092
        networks: 
            tap:
                ipv4_address: "10.0.100.23"

    spark:
        build: spark/
        container_name: "mc-spark"
        depends_on: 
            - zookeeper
            - kafka
        networks: 
            tap:
                ipv4_address: "10.0.100.28"
    
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.1"
        container_name: "mc-elasticsearch"
        environment:
            discovery.type: single-node
        ulimits:
            memlock:
              soft: -1
              hard: -1
        ports:
            - 9200:9200
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data/
        networks: 
            tap:
                ipv4_address: "10.0.100.51"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.1
        container_name: "mc-kibana"
        environment:
            SERVER_NAME: kibana
            ELASTICSEARCH_HOSTS: "http://10.0.100.51:9200"
        ports: 
            - 5601:5601
        networks: 
            tap:
                ipv4_address: "10.0.100.52"

volumes: 
    elasticsearch:

networks: 
    tap:
        ipam:
            driver: default
            config: 
                - subnet: 10.0.100.0/24 